"""Builds an explicit trainer order for a calc, from a Nuzlocke Documentation
Site areas.json.

    python3 tools/gen_trainer_order.py <backup-key> "<title>" <areas.json>

Appends/updates js/data/trainer_order.js, which both showdown_hooks.js
(deriveTrainerOrder) and tools/gen_mastersheet.py read. Emitting one list that
both consume is the point: the mastersheet indexes trainers by position, so if
the two ever disagree the Next button silently loads the wrong trainer.

The calc data carries no field for where you meet a trainer. class_id is the
trainer class and p_id is the lead's species, so order has to come from
somewhere else. areas.json lists areas in game order with their rosters, which
is exactly that missing information.

Not every calc trainer appears there: rematches and unnamed "[~ N]" entries do
not. Those get slotted in by ace level, which rises steadily along game order,
so they land in roughly the right stretch of the game rather than at the end.
"""
import bisect
import collections
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST = os.path.join(REPO, "js", "data", "trainer_order.js")


def calc_trainers(key):
    """trainer name -> ace level, from the calc's own set data."""
    with open(os.path.join(REPO, "backups", "%s.js" % key), encoding="utf-8") as f:
        raw = f.read()
    data = json.loads(raw[raw.index("{"):].rstrip().rstrip(";"))

    levels = collections.defaultdict(list)
    for sets in data["formatted_sets"].values():
        for set_name in sets:
            m = re.match(r"^Lvl\s+(\d+)\s+(.*)$", set_name.strip())
            if m:
                levels[m.group(2).strip()].append(int(m.group(1)))
    return {name: max(lv) for name, lv in levels.items()}


def normalise(name):
    name = name.replace("PKMN Trainer", "Pokémon Trainer")
    name = re.sub(r"\s*\[[^\]]*\]\s*$", "", name)   # drop "[Cynthia]" style notes
    name = name.replace("Manaic", "Maniac")          # typo in the doc source
    return re.sub(r"\s+", " ", name).strip().lower()


def doc_order(areas_path, trainers):
    """Calc trainer names in game order, for those the doc site lists."""
    with open(areas_path, encoding="utf-8") as f:
        areas = json.load(f)["areas"]

    by_norm = collections.defaultdict(list)
    for name in trainers:
        by_norm[normalise(name)].append(name)

    seen, ordered = set(), []
    for area in areas:
        for roster in (area.get("rosters") or []):
            for trainer in (roster.get("trainers") or []):
                key = normalise(trainer.get("name") or "")
                if key in by_norm and key not in seen:
                    seen.add(key)
                    ordered.extend(sorted(by_norm[key]))
    return ordered


def build(key, title, areas_path):
    trainers = calc_trainers(key)
    ordered = doc_order(areas_path, trainers)
    placed = set(ordered)

    # Slot the rest by where their ace ranks among the placed trainers, rather
    # than by walking a running max of the sequence. A single name collision
    # (the doc site lists an early route Rich Boy Winston, the calc only has his
    # level 75 rematch) would otherwise spike that running max and dump every
    # later trainer into one bucket. Ranking shifts by one position instead.
    placed_aces = sorted(trainers[name] for name in ordered)

    leftovers = collections.defaultdict(list)
    for name, ace in sorted(trainers.items(), key=lambda kv: (kv[1], kv[0])):
        if name in placed:
            continue
        leftovers[bisect.bisect_right(placed_aces, ace)].append(name)

    final = []
    for i, name in enumerate(ordered):
        final.extend(leftovers.get(i, []))
        final.append(name)
    final.extend(leftovers.get(len(ordered), []))

    orders = {}
    if os.path.exists(DEST):
        with open(DEST, encoding="utf-8") as f:
            existing = f.read()
        m = re.search(r"trainerOrders = (\{.*\})", existing, re.S)
        if m:
            orders = json.loads(m.group(1))
    orders[title] = final

    with open(DEST, "w", encoding="utf-8") as f:
        f.write("// Trainer order in the sequence you meet them.\n")
        f.write("// Generated by tools/gen_trainer_order.py - do not hand edit.\n")
        f.write("// Read by deriveTrainerOrder in js/showdown_hooks.js and by\n")
        f.write("// tools/gen_mastersheet.py, which must agree on positions.\n\n")
        f.write("trainerOrders = " + json.dumps(orders, ensure_ascii=False, indent=1) + "\n")

    print("calc trainers: %d" % len(trainers))
    print("placed from areas.json: %d" % len(ordered))
    print("slotted by ace level: %d" % (len(final) - len(ordered)))
    assert len(final) == len(trainers), "lost trainers: %d vs %d" % (len(final), len(trainers))
    assert len(set(final)) == len(final), "duplicate trainers in order"
    print("wrote %s (%d trainers for %s)" % (DEST, len(final), title))


if __name__ == "__main__":
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    build(sys.argv[1], sys.argv[2], sys.argv[3])
